# Generated by Django 6.0.3 on 2026-03-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='sale_group',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Группа продажи'),
        ),
    ]
