# Generated by Django 6.0.3 on 2026-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0002_history_total_price_product_barcode_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина'),
        ),
    ]
