# Generated by Django 6.0.3 on 2026-04-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0002_pricelist_product_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Если не указана, используется базовая цена с множителем', max_digits=10, null=True, verbose_name='Своя цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cash_app.pricelist', verbose_name='Прайс-лист')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='cash_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в прайс-листе',
                'verbose_name_plural': 'Товары в прайс-листах',
                'unique_together': {('price_list', 'product')},
            },
        ),
    ]
