# Generated by Django 6.0.3 on 2026-03-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0002_history_sale_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Количество'),
        ),
    ]
