# Generated by Django 6.0.3 on 2026-03-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0003_alter_history_quantity_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash_app.product', verbose_name='Товар'),
        ),
    ]
