# Generated by Django 6.0.3 on 2026-04-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0004_storeaddress_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash_app.storeaddress', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Множитель цены'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Своя цена'),
        ),
    ]
