# Generated by Django 6.0.3 on 2026-04-03 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0005_history_store_alter_pricelist_multiplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оклад')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='Процент от выручки сотрудника', max_digits=5, verbose_name='Процент от продаж')),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=0, help_text='Дополнительный процент при выполнении плана', max_digits=5, verbose_name='Премиальная часть')),
                ('plan_completion_threshold', models.DecimalField(decimal_places=2, default=100, help_text='Минимальный процент выполнения плана для получения премии', max_digits=5, verbose_name='Порог выполнения плана для премии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_updates', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_settings', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Настройка зарплаты',
                'verbose_name_plural': 'Настройки зарплат',
            },
        ),
        migrations.CreateModel(
            name='SalaryCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оклад')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Комиссия от продаж')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Премия')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого к выплате')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая выручка за месяц')),
                ('plan_completion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Выполнение плана')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('calculated', 'Рассчитано'), ('paid', 'Выплачено')], default='draft', max_length=20, verbose_name='Статус')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_calculations', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Расчет зарплаты',
                'verbose_name_plural': 'Расчеты зарплат',
                'ordering': ['-year', '-month', 'user__username'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
