# Generated by Django 6.0.3 on 2026-04-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0006_salarysettings_salarycalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Закупочная цена товара', max_digits=10, verbose_name='Себестоимость'),
        ),
    ]
