# Generated by Django 6.0.3 on 2026-04-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_app', '0007_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_composite',
            field=models.BooleanField(default=False, help_text='Отметьте, если это блюдо, которое готовится из ингредиентов', verbose_name='Составное блюдо'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Закупочная цена товара (для ингредиентов) или рассчитанная (для блюд)', max_digits=10, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг'), ('g', 'г'), ('ml', 'мл')], default='pcs', max_length=3, verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_quantity', models.DecimalField(decimal_places=3, default=1, help_text='Количество готового продукта из рецепта (например, 1 порция = 1 шт)', max_digits=10, verbose_name='Выход продукта')),
                ('cooking_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время приготовления (мин)')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкция по приготовлению')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='cash_app.product', verbose_name='Готовое блюдо')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Примечания')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash_app.product', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='cash_app.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецептов',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
